name: bar_code_scanner
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5

  flutter_barcode_scanner: ^2.0.0   # Scanner plugin
  dartz: ^0.10.1                    # Functional Programming
  get_it: ^7.2.0                    # Service locator
  flutter_svg: ^1.1.6               # SVG reader

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: fonts/lato/Lato-Italic.ttf
          style: italic
    
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
      